```javascript
// 抛出异常,可以抛出任意表达式
// throw "Error2";   // String type
// throw 42;         // Number type
// throw true;       // Boolean type
// throw {toString: function() { return "I'm an object!"; } };

// try...catch
try {
    var a;
    if (a === undefined){
        throw 'myError'; // 这里抛出错误
    }
} catch(e) {
    console.log(e); // 捕捉到错误,输出 myError
} finally {
    console.log('永远都会执行');
}

try {
    var a;
    if (a === undefined){
        throw (new Error('myError')); // 新建一个Error
    }
} catch(e) {
    console.log(e.name); // 输出Error (错误类型)
    console.log(e.message); // 输出 myError (错误信息)
} finally {
    console.log('永远都会执行');
}

```
